In [0]:
import pandas as pd
import numpy as np
df=pd.read_csv('diuersis.csv')

TESTING THE BEST MODEL


In [0]:
df['26-Mar-20'] = df['26-Mar-20'].str.replace(",","").astype(float)
df['25-Mar-20'] = df['25-Mar-20'].str.replace(",","").astype(float)
df['24-Mar-20'] = df['24-Mar-20'].str.replace(",","").astype(float)

In [7]:
df.dtypes

people_ID      int64
20-Mar-20      int64
21-Mar-20      int64
22-Mar-20      int64
23-Mar-20      int64
24-Mar-20    float64
25-Mar-20    float64
26-Mar-20    float64
dtype: object

In [0]:
df.drop(['people_ID'],axis=1,inplace=True)

In [0]:
data=np.array(df)

In [12]:
data.shape[0]

10714

In [0]:
def create_dataset(data, k):
    dataX, dataY = [],[]
    for j in range(0,data.shape[0]):
      for i in range(6):
          x = data[j][i:i + k]
          y = data[j][i + k]
          dataX.append(x)
          dataY.append(y)
    return np.array(dataX), np.array(dataY)

In [0]:
trainX, trainY = create_dataset(data, 1)

In [15]:
trainX.shape

(64284, 1)

In [16]:
trainY

array([544., 670., 821., ..., 455., 559., 687.])

In [17]:
from sklearn.model_selection import train_test_split
trainX, testX, y_train, y_test = train_test_split(data, y, test_size=0.2, random_state=50)

NameError: ignored

In [18]:
trainX=np.array(trainX)
testX=np.array(testX)

NameError: ignored

In [19]:
trainX = np.reshape(trainX, (trainX.shape[0], trainX.shape[1],1))
testX = np.reshape(testX, (testX.shape[0], testX.shape[1],1))
trainX.shape

NameError: ignored

In [21]:
from keras.models import Sequential
from keras.layers import LSTM, Dense
import keras.layers

Using TensorFlow backend.


In [0]:
model = Sequential()
model.add(keras.layers.SimpleRNN(4, input_shape=(6, 1)))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(trainX, y_train, epochs=10, batch_size = 1)

Epoch 1/10
8571/8571 [==============================] - 15s 2ms/step - loss: 1008146.0044
Epoch 2/10
8571/8571 [==============================] - 14s 2ms/step - loss: 931565.0063
Epoch 3/10
8571/8571 [==============================] - 14s 2ms/step - loss: 858553.1967
Epoch 4/10
8571/8571 [==============================] - 14s 2ms/step - loss: 789216.9737
Epoch 5/10
8571/8571 [==============================] - 14s 2ms/step - loss: 723505.0828
Epoch 6/10
8571/8571 [==============================] - 14s 2ms/step - loss: 661244.4732
Epoch 7/10
8571/8571 [==============================] - 14s 2ms/step - loss: 602721.7997
Epoch 8/10
8571/8571 [==============================] - 14s 2ms/step - loss: 547718.6488
Epoch 9/10
8571/8571 [==============================] - 14s 2ms/step - loss: 496215.7776
Epoch 10/10
8571/8571 [==============================] - 14s 2ms/step - loss: 448301.4858


In [20]:
NUM_NEURONS_FirstLayer = 100
NUM_NEURONS_SecondLayer = 50
EPOCHS = 200
model = Sequential()
model.add(LSTM(NUM_NEURONS_FirstLayer,input_shape=(6,1), return_sequences=True))
model.add(LSTM(NUM_NEURONS_SecondLayer,input_shape=(NUM_NEURONS_FirstLayer,1)))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
history = model.fit(trainX,y_train,epochs=EPOCHS,shuffle=True,batch_size=10, verbose=2)

NameError: ignored

In [0]:
pred=model.predict(testX)
pred=np.reshape(pred,(2143))

In [0]:
print("Mean Absolute Error:", np.mean(np.absolute(pred-y_test)))


Mean Absolute Error: 4.200725945255994


In [0]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,pred)
print(r2)

0.9997108356565467


Prediction 

In [0]:
data=df[df.columns[1:-1]]

In [0]:
y=df[df.columns[-1]]

In [0]:
data1=np.array(data)

In [24]:
data1 = np.reshape(trainX, (trainX.shape[0], trainX.shape[1],1))
data1.shape

(64284, 1, 1)

In [54]:
NUM_NEURONS_FirstLayer = 100
NUM_NEURONS_SecondLayer = 50
EPOCHS = 100
model = Sequential()
model.add(LSTM(NUM_NEURONS_FirstLayer,input_shape=(1,1), return_sequences=True))
model.add(LSTM(NUM_NEURONS_SecondLayer,input_shape=(NUM_NEURONS_FirstLayer,1)))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
history = model.fit(data1,trainY,epochs=EPOCHS,shuffle=True,batch_size=50, verbose=2)
from sklearn.externals import joblib 

# Save the model as a pickle in a file 
joblib.dump(model, 'filename.pkl')

Epoch 1/100
 - 8s - loss: 441101.6148
Epoch 2/100
 - 7s - loss: 383979.0509
Epoch 3/100
 - 7s - loss: 334438.9709
Epoch 4/100
 - 7s - loss: 290257.4928
Epoch 5/100
 - 7s - loss: 250899.8236
Epoch 6/100
 - 7s - loss: 216193.3065
Epoch 7/100
 - 7s - loss: 186003.9273
Epoch 8/100
 - 7s - loss: 160258.7582
Epoch 9/100
 - 7s - loss: 138886.7291
Epoch 10/100
 - 7s - loss: 121707.7595
Epoch 11/100
 - 7s - loss: 108593.5571
Epoch 12/100
 - 7s - loss: 99226.7108
Epoch 13/100
 - 7s - loss: 93220.2277
Epoch 14/100
 - 7s - loss: 89967.2851
Epoch 15/100
 - 7s - loss: 88648.8248
Epoch 16/100
 - 7s - loss: 88290.9719
Epoch 17/100
 - 7s - loss: 88229.0306
Epoch 18/100
 - 7s - loss: 88221.9526
Epoch 19/100
 - 7s - loss: 88220.7234
Epoch 20/100
 - 7s - loss: 53986.3200
Epoch 21/100
 - 7s - loss: 37039.5769
Epoch 22/100
 - 7s - loss: 29679.2735
Epoch 23/100
 - 7s - loss: 23873.2842
Epoch 24/100
 - 7s - loss: 19119.8798
Epoch 25/100
 - 7s - loss: 15215.4855
Epoch 26/100
 - 7s - loss: 12033.4177
Epoch 27/1

['filename.pkl']

In [0]:
datapre=df[df.columns[2:]]

In [0]:
datapre

21-Mar-20  22-Mar-20  23-Mar-20  24-Mar-20  25-Mar-20  26-Mar-20
0            544        670        821     1002.0     1216.0     1473.0
1            197        253        322      400.0      493.0      607.0
2            515        632        777      948.0     1150.0     1396.0
3            506        621        762      928.0     1127.0     1368.0
4            483        595        730      893.0     1084.0     1316.0
...          ...        ...        ...        ...        ...        ...
10709        174        225        288      359.0      444.0      549.0
10710        479        592        725      885.0     1075.0     1303.0
10711        228        288        362      448.0      551.0      677.0
10712        438        543        666      815.0      991.0     1204.0
10713        230        290        366      455.0      559.0      687.0

[10714 rows x 6 columns]

In [0]:
datapre = np.reshape(datapre, (datapre.shape[0], datapre.shape[1],1))
pred=model.predict(datapre)

ValueError: ignored

In [0]:
test=pd.read_csv('Test_dataset.csv')

In [0]:
a=test['Diuresis']

In [0]:
a=np.array(a)

In [62]:
final=[]
for j in range(0,a.shape[0]):
  pred=[[a[j]]]
  print(j)
  for i in range(0,7):
    pred=model.predict([[pred]])
  final.append(pred[0][0])

Streaming output truncated to the last 5000 lines.
9499
9500
9501
9502
9503
9504
9505
9506
9507
9508
9509
9510
9511
9512
9513
9514
9515
9516
9517
9518
9519
9520
9521
9522
9523
9524
9525
9526
9527
9528
9529
9530
9531
9532
9533
9534
9535
9536
9537
9538
9539
9540
9541
9542
9543
9544
9545
9546
9547
9548
9549
9550
9551
9552
9553
9554
9555
9556
9557
9558
9559
9560
9561
9562
9563
9564
9565
9566
9567
9568
9569
9570
9571
9572
9573
9574
9575
9576
9577
9578
9579
9580
9581
9582
9583
9584
9585
9586
9587
9588
9589
9590
9591
9592
9593
9594
9595
9596
9597
9598
9599
9600
9601
9602
9603
9604
9605
9606
9607
9608
9609
9610
9611
9612
9613
9614
9615
9616
9617
9618
9619
9620
9621
9622
9623
9624
9625
9626
9627
9628
9629
9630
9631
9632
9633
9634
9635
9636
9637
9638
9639
9640
9641
9642
9643
9644
9645
9646
9647
9648
9649
9650
9651
9652
9653
9654
9655
9656
9657
9658
9659
9660
9661
9662
9663
9664
9665
9666
9667
9668
9669
9670
9671
9672
9673
9674
9675
9676
9677
9678
9679
9680
9681
9682
9683
9684
9685
9686
9687
9688

In [63]:
print(final)

[1469.822, 1472.7457, 1474.3944, 1032.5492, 1113.8514, 1439.4092, 928.5249, 1298.1224, 1465.6471, 1474.4524, 1468.4166, 1467.2947, 1275.644, 945.9385, 914.1982, 821.8097, 1441.9244, 1473.9977, 1357.6892, 1382.5908, 1402.9368, 1058.2649, 846.9115, 1466.3452, 1433.9536, 1313.4763, 1443.1322, 757.4487, 1471.9102, 1079.9818, 1474.3324, 850.6196, 976.5214, 949.36884, 1472.9163, 976.5214, 1473.8131, 1058.2649, 1361.0496, 1466.9896, 1474.1958, 1158.8502, 903.20447, 962.9802, 1474.2998, 1461.2593, 760.79236, 1190.6385, 1457.8673, 1298.1224, 1473.4216, 1247.385, 1422.8737, 1472.255, 869.38617, 1474.6305, 1469.6106, 846.9115, 1181.8624, 727.7941, 1400.6278, 1309.6295, 1466.3452, 1471.5206, 1470.7565, 910.55597, 1214.8566, 1471.2333, 1129.464, 942.4929, 1079.9818, 1473.8131, 1158.8502, 1473.4216, 740.8313, 1474.5583, 1097.358, 1018.0867, 1474.0809, 1472.0297, 903.20447, 1438.1, 1153.0908, 1158.8502, 801.1412, 1469.6106, 1393.3097, 821.8097, 1065.5754, 1449.7455, 825.3225, 1473.5436, 1317.3204, 11

In [0]:
train=pd.read_csv('Train_dataset.csv')

In [0]:
train.dropna()

In [0]:
da=train['Diuresis']

In [66]:
train

people_ID        Region  Gender  ...   salary FT/month Infect_Prob
0              1  Bhubaneshwar  Female  ...  1300000      2.0   49.135010
1              2  Bhubaneshwar  Female  ...   400000      1.0   51.147880
2              3  Bhubaneshwar  Female  ...   900000      1.0   73.224000
3              4  Bhubaneshwar  Female  ...  2300000      1.0   48.779225
4              5  Bhubaneshwar  Female  ...  1100000      1.0   87.868800
...          ...           ...     ...  ...      ...      ...         ...
10709      22691     Bengaluru    Male  ...   300000      0.0   41.981760
10710      22692     Bengaluru    Male  ...   700000      NaN   47.148663
10711      22693     Bengaluru    Male  ...  2100000      2.0   47.708533
10712      22694     Bengaluru    Male  ...   700000      1.0   53.803565
10713      22695     Bengaluru    Male  ...  1400000      0.0   68.342400

[10714 rows x 28 columns]

In [0]:
y=train['Infect_Prob']

In [0]:
bigdata = pd.concat([da,y], axis=1)

In [0]:
bigdata.dropna(inplace=True)

In [0]:
y=bigdata['Infect_Prob']
da=bigdata['Diuresis']

In [0]:
from sklearn.ensemble import RandomForestRegressor

In [0]:
regr = RandomForestRegressor(max_depth=1000, random_state=10)

In [0]:
da=np.array(da)
y=np.array(y)
da=da.reshape(-1,1)
y=y.reshape(-1,1)

In [81]:
regr.fit(da,y)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=1000, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=10, verbose=0, warm_start=False)

In [0]:
final=np.array(final).reshape(-1,1)
y_pred1=regr.predict(final)

In [85]:
y_pred1

array([51.1535104, 51.1535104, 51.1535104, ..., 51.1535104, 51.1535104,
       51.1535104])

In [86]:
from sklearn import linear_model
slr=linear_model.LinearRegression()

slr.fit(da,y)
print("coeficnet:",slr.coef_)
print("Intercept:",slr.intercept_)

coeficnet: [[0.00077257]]
Intercept: [52.04582003]


In [0]:
test_result=slr.predict(final)

In [109]:
test_result[1400]

array([53.18436639])

In [0]:
from pprint import pprint
from sklearn import neighbors
from sklearn.neighbors import KNeighborsClassifier
regressor=neighbors.KNeighborsRegressor(n_neighbors=100)

In [91]:
regressor.fit(da,y)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=100, p=2,
                    weights='uniform')

In [0]:
y_pred1=regressor.predict(final)

In [93]:
y_pred1

array([[51.76798389],
       [51.76798389],
       [51.76798389],
       ...,
       [51.76798389],
       [51.76798389],
       [51.76798389]])

In [0]:
from sklearn.svm import SVR

In [0]:
clf = SVR(C=10.0, epsilon=0.2)

In [101]:
clf.fit(da,y)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=10.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.2, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [0]:
y_pred1=clf.predict(final)

In [103]:
y_pred1

array([49.1900943 , 49.1900943 , 49.1900943 , ..., 49.19009401,
       49.19009429, 49.18814788])

In [0]:
s=train['people_ID'].append(pd.DataFrame(test_result))

In [0]:
bigdata = pd.concat([train['people_ID'], pd.DataFrame(test_result)], axis=1)

In [0]:
bigdata.to_csv(r'outputfile-02.csv', index = False)

In [0]:
 b